### ISSUE TITLE
undefined local variable or method `has_merit'

### ISSUE THREAD

**Issue by arjenbrandenburgh** [merit-gem/merit#175]
When trying to install the merit gem, the following error occurs when doing the rake db:migrate.

```
undefined local variable or method `has_merit' for User(no database connection): Class
D:/sites/xxx/app/models/user.rb:2:in `<class:User>'
D:/sites/xxx/app/models/user.rb:1:in `<top (required)>'
D:/sites/xxx/lib/user_sanitizer.rb:1:in `<top (required)>'
D:/sites/xxx/config/initializers/sanitizers.rb:1:in `<top (required)>'
D:/sites/xxx/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

I'm running ruby 1.9.3, rails 4.0.1 on Windows 7 with a postgres database.

Let me know if you need additional information.

**Comment by MarinaMartin** [comment]
I experienced this same issue with Rails 4.2, and removing the ClassSanitizer solved the problem.

**Comment by UriKatz** [comment]
I had a similar issue. Traced it back to RailsAdmin configuring my user model in an initializer. Fixed it by making sure the Merit initializer load first (initializers load according to the alphanumeric order of thier file name).

**Comment by tute** [comment]
Potentially useful to others:

> Traced it back to RailsAdmin configuring my user model in an initializer. Fixed it by making sure the Merit initializer load first (initializers load according to the alphanumeric order of thier file name).

**Comment by fiedl** [comment]
I had to `include Merit` in order to resolve this.

```ruby
class User < ActiveRecord::Base
  include Merit
  has_merit                 

end
```

Version info:

```bash
➜  ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

➜  be rails --version
Rails 4.2.3

➜  grep merit Gemfile.lock
      merit
    merit (2.3.2)
```

**Comment by tute** [comment]
Somewhere around https://github.com/merit-gem/merit/blob/master/lib/merit.rb#L108-L110 lies a bug.

**Comment by pacMakaveli** [comment]
Just wanted to confirm that adding `include Merit` in my User model fixed my issue when running a rails task on the User model.

**Comment by tute** [comment]
@pacMakaveli do you think we can fix this in merit's codebase?

**Comment by pacMakaveli** [comment]
@tute I can definitely have a look and see what's causing this. I had no issues on Rails < 5.rc1 . I've done a big bundle update very recently and this issue started to come up.
I will have a play tonight and later this week and I will update you with any findings.

**Comment by pacMakaveli** [comment]
Ok, **my** problem is a conflict between `merit` and `thredded` ( a forum engine ) .. after removing `thredded` from the gemfiles and the application everything works fine.

I know this is isolated to my case since, most likely, no one else here is using `thredded` . My guess is an engine conflicts with merit.. since it's the only gem that causes this issue.

It would help if anyone else posts their gemfile to see if it's indeed caused by another engine gem.

I will look into thredded's codebase and see if I can find something.

@tute

**Comment by pacMakaveli** [comment]
@tute nothing to fix. The problem lied with Thredded misusing `current_user`. Once that has been corrected, both gems work fine together and there's no need for `include Merit` in the `User` model.

@all I'm happy to look at this again if the issue is still present. The problem lies in using `current_user` helper wrong.

**Comment by cbortz** [comment]
Hey @pacMakaveli I am wondering if you could explain a bit how Thredded is using the current_user helper wrong. I am experimenting with these two gems and I ran across this specific error.

Have you looked at the Thredded codebase? Do you have any idea how it could be fixed?

**Comment by pacMakaveli** [comment]
@cbortz I haven't had the chance to properly look into Thredded's source code. But I'll be happy to look into this issue once I put Thredded back into my application. No ETA I'm afraid.

**Comment by cbortz** [comment]
@pacMakaveli No worries my friend. At least knowing that the issue is already documented puts me a bit at ease! 👍
