### ISSUE TITLE
Partially processing badges?

### ISSUE THREAD

**Issue by durkie** [merit-gem/merit#293]
Hello -- thanks for the nice work with this gem. I'm using it in a situation where I have about 1100 badges at the moment and I will hopefully be adding many more. Because there are so many badges, I run in to two situations:
* `merit_activity_logs` gets really big really fast
* processing badges takes a really long time.

Can you think of a way where I could decide which badges get processed at a time? Like could I subclass Merit::Badge or something and Merit::Action and then run only those at given times? The processing action takes a little bit of time, so I have it run semi-regularly with `Merit::Action.check_unprocessed` and this just checks a user against all possible badges, even though in most situations I know which ones will be relevant.

Thanks! (And I realize this isn't really an issue -- jus wasn't sure the best place to put this)

**Comment by tute** [comment]
Hi @durkie. I am glad merit has been useful to you!

> `merit_activity_logs` gets really big really fast

How big is it now? How does it become a problem for you? If we find the need for an API to disable it, we may discuss creating a PR so that somehow the `Merit::ReputationChangeObserver` can be disabled. And if we don't think it's worth it to abstract it into merit, maybe a periodic cleaner for that table would suffice?

> processing badges takes a really long time.

Just out of curiosity, how long does it take? Does it take a toll on page load times?

> Can you think of a way where I could decide which badges get processed at a time? Like could I subclass Merit::Badge or something and Merit::Action and then run only those at given times?

I'm surprised you'd need this, as merit already scopes what rules get processed according to the action performed in your application. Do you have ~1k badges potentially granted, all on the same controller action of your app? Can you share your `merit.rb` initializer so we study in more detail?

Thanks!

**Comment by durkie** [comment]
I'm probably using merit in a weird way, but I'm building a kind of a location-based game, so my app awards badges around geospatial data. Because of this, it doesn't work to run merit in response certain controller actions because nothing will change until new data comes in. When new data arrive, I manually add a merit action for that user (via `Merit::Action.create(..)`) and then run `Merit::Action.check_unprocessed`. This all happens in a background job. This is nice too because there are some geometric computations to be done to determine if a badge can be awarded, so page-load doesn't block while merit is running. It currently takes about 25-30 seconds per user to run through all of the badges. This can likely be reduced -- many of the badges are currently "temporary", so they get evaluated each time and some of those can probably be changed.

But regardless: the situation I face is that when I receive geographic data that I know is confined to a certain area, it doesn't make sense to evaluate if a badge outside of that area should be awarded. So that's my original question of can I limit badge judgment to certain group of badges. Even if I get rid of all temporary badges, European users most likely won't need to be evaluated for North American badges, etc. I have 1100 badges now, but am hoping to have 100-1000x that.

And I am currently cleaning the `merit_activity_logs` table occasionally. The large number of temporary badges probably contributes to more logs entries here too.

(happy to send you my `merit.rb` and `badge_rules.rb` fies if that's helpful -- just didn't want to attach them here because each is several hundred lines)

**Comment by tute** [comment]
It sounds like your use case streches merit's design, but I'll describe as best I can how I would use merit for your app as you describe.

> it doesn't work to run merit in response certain controller actions because nothing will change until new data comes in. When new data arrive, I manually add a merit action for that user (via `Merit::Action.create(..)`) and then run `Merit::Action.check_unprocessed`.

Instead of defining merit rules and then running the checker, what do you think of creating services to grant reputation per continent? For example, when a condition happens in your app that might grant a badge in Spain, you write something like:

```ruby
if conditions_for_this_badge_apply?(params, current_user, anything_needed)
  current_user.add_badge(badge.id)
end
```

That is, inline merit into your app intead of having it as an external engine that observes merit actions. Refactor out as services as needed.

See: https://github.com/merit-gem/merit#other-actions.

> I have 1100 badges now, but am hoping to have 100-1000x that.

Each time you add a badge you have to redeploy, right? Because they are defined statically in that one initializer. This solution I like because I considered having the badges necessary for the app to run; when you have a couple dozen badges if one is not there I was ok with the app failing, or needing to redeploy for a new reputation rule and badge addiiton. But in your case you might prefer storing them in a database. And that is too much a departure from merit, and at that point you wouldn't use much of the gem, but still may prove useful.

What are your thoughts? Thanks for sharing!

**Comment by durkie** [comment]
Thanks for you thoughts on this. I hadn't considered that I would be needing to redeploy for each new badge in the future. I think that's a great idea to start inlining merit and incorporating it in to various services with different geographical scopes. From there, perhaps it will be easier to transition to storing badges in a database when/if that becomes necessary.

**Comment by tute** [comment]
Sounds good. Closing this issue for now as it doesn't seem an issue within merit, but happy to continue discussing. Thanks!
