### ISSUE TITLE
 Merit 4.0 causing Heroku deployment errors

### ISSUE THREAD

**Issue by gabrielguerin** [merit-gem/merit#343]
I followed these two tutorials: [How to show last granted badges](https://github.com/merit-gem/merit/wiki/How-to-show-last-granted-badges) & [How to show a points leaderboard](https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard). Since Merit got updated to 4.0, it created these errors when deploying to Heroku: `TypeError: superclass mismatch for class BadgesSash` & `TypeError: superclass mismatch for class Score`. Setting Merit to 3.0.3 in the Gemfile like this: `gem 'merit', '~> 3.0.3'` temporarily corrected the problem. Do you know why it is doing this?

**Comment by tute** [comment]
Yep, that's one of the reasons it's a breaking change, due to this commit: https://github.com/merit-gem/merit/commit/9f1b6b0089b47e188018c7e1725db43842ae6586

For example, the new namespace for `Score` is `Merit::Models::ActiveRecord`. We have to update the docs listing the different namespaces according to merit version; for now I leave this pointer here as I won't be able to do it in the short term.

Thanks for asking!

**Comment by gabrielguerin** [comment]
@tute Thank you for your reply. So how should I changed my files created while following these tutorials :  [How to show last granted badges](https://github.com/merit-gem/merit/wiki/How-to-show-last-granted-badges) & [How to show a points leaderboard](https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard)?

**Comment by tute** [comment]
Does it work if you remove the ` < ActiveRecord::Base` part in both cases? If so, that's a syntax that will work with either version of merit.

**Comment by gabrielguerin** [comment]
@tute just tried what you suggested and it worked perfectly! Thank you very much!
